## Accuracy on target

In [1]:
%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("5050_kids_train_cleaned.csv")
df.drop(df.columns[0], axis=1, inplace=True)
df.drop(df.columns[0], axis=1, inplace=True)
df.head()

,RefId,PurchDate,Auction,VehYear,VehicleAge,Make,Model,Trim,SubModel,Color,...,PurchDay,PurchWeekDay,EngineLiters,NumCylinders,4X4,WheelDrive,NumDoors,PCA1,PCA2,IsBadBuy
0,9484,6/29/2009,MANHEIM,2004.0,5.0,KIA,SPECTRA,EX,SEDAN,GOLD,...,29.0,Monday,2.000000,4.0,0,0,4.0,-12583.504418,956.191948,0
1,47185,9/15/2009,MANHEIM,2005.0,5.0,CHRYSLER,ION,Tou,SEDAN,SILVER,...,21.0,Tuesday,3.179050,8.0,0,0,4.0,2577.708270,-1445.484267,0
2,52559,11/3/2010,OTHER,2008.0,2.0,MAZDA,MAZDA3,i,SPORT,SILVER,...,3.0,Wednesday,4.278157,7.0,0,0,4.0,14832.457604,465.552450,0
3,52150,7/30/2010,MANHEIM,2007.0,3.0,CHRYSLER,PT CRUISER,LE,SEDAN,SILVER,...,24.0,Friday,1.660941,4.0,0,0,4.0,14200.129833,-586.242603,0
4,36222,6/3/2009,MANHEIM,2004.0,5.0,KIA,OPTIMA,EX,SEDAN,BLACK,...,3.0,Wednesday,2.400000,4.0,0,0,4.0,-10380.306456,1254.054165,0

In [3]:
for e in df.columns:
    print(e)

RefId
PurchDate
Auction
VehYear
VehicleAge
Make
Model
Trim
SubModel
Color
Transmission
WheelType
VehOdo
Nationality
AAAP
AACP
ARAP
ARCP
CAAP
CACP
CRAP
CRCP
BYRNO
VNST
VehBCost
WarrantyCost
PurchYear
PurchMonth
PurchDay
PurchWeekDay
EngineLiters
NumCylinders
4X4
WheelDrive
NumDoors
PCA1
PCA2
IsBadBuy

In [4]:
categories = ['Model', 'Make', 'Trim', 'BYRNO', 'WheelType', 'Color', 'VNST','IsBadBuy']

not_cat = ['VehOdo', 'VehBCost', 'WarrantyCost', 'AAAP', 'VehicleAge']

to_drop = ['AACP', 'ARAP', 'ARCP', 'CAAP', 'CACP', 'CRAP', 'CRCP', 'NumCylinders', '4X4', 'WheelDrive',
           'NumDoors', 'PCA1', 'PCA2', 'RefId', 'PurchDate', 'PurchYear', 'PurchMonth',
            'PurchDay', 'VehYear', 'EngineLiters', 'Auction', 'PurchWeekDay',
'Transmission', 'Nationality','SubModel']

In [5]:
df.drop(columns= to_drop, axis=1, inplace=True)

In [6]:
df.head()

,VehicleAge,Make,Model,Trim,Color,WheelType,VehOdo,AAAP,BYRNO,VNST,VehBCost,WarrantyCost,IsBadBuy
0,5.0,KIA,SPECTRA,EX,GOLD,Covers,71548,3161.0,20740,NC,4635.0,569,0
1,5.0,CHRYSLER,ION,Tou,SILVER,Covers,83039,3947.0,22808,TX,9350.0,1503,0
2,2.0,MAZDA,MAZDA3,i,SILVER,Alloy,49500,10477.0,99761,NH,7965.0,764,0
3,3.0,CHRYSLER,PT CRUISER,LE,SILVER,Covers,95093,10262.0,18822,TX,4735.0,1630,0
4,5.0,KIA,OPTIMA,EX,BLACK,Alloy,59251,3402.0,20207,TX,5060.0,671,0

In [7]:
for col in categories:
    df[col] = df[col].astype('category')
    
df['VehicleAge'] = df['VehicleAge'].astype('int')

In [8]:
sum_ = df.isnull().sum()
sum_[sum_ != 0]

Series([], dtype: int64)

## BINNING

In [10]:
bins = [df.VehBCost.min() - 1,5000, 7000, 8000, 10000, df.VehBCost.max()]

df['VehBCost'] = pd.cut(df['VehBCost'], bins)

In [12]:
bins = [df.AAAP.min() - 1, 3000, 6000, 8000, 10000, df.AAAP.max()]

df['AAAP'] = pd.cut(df['AAAP'], bins)

In [14]:
bins = [df.WarrantyCost.min() - 1,700, 1200, 1800, 2600, df.WarrantyCost.max()]

df['WarrantyCost'] = pd.cut(df['WarrantyCost'], bins)

In [16]:
bins = [df.VehOdo.min() - 1,40000, 60000, 80000, 100000, df.VehOdo.max()]

df['VehOdo'] = pd.cut(df['VehOdo'], bins)

In [17]:
df['VehicleAge'] = pd.cut(df['VehicleAge'], [0, 2, 4, 6, 8, 10], right=False)

In [18]:
df.head()

,VehicleAge,Make,Model,Trim,Color,WheelType,VehOdo,AAAP,BYRNO,VNST,VehBCost,WarrantyCost,IsBadBuy
0,"[4, 6)",KIA,SPECTRA,EX,GOLD,Covers,"(60000, 80000]","(3000.0, 6000.0]",20740,NC,"(224.0, 5000.0]","(461, 700]",0
1,"[4, 6)",CHRYSLER,ION,Tou,SILVER,Covers,"(80000, 100000]","(3000.0, 6000.0]",22808,TX,"(8000.0, 10000.0]","(1200, 1800]",0
2,"[2, 4)",MAZDA,MAZDA3,i,SILVER,Alloy,"(40000, 60000]","(10000.0, 35722.0]",99761,NH,"(7000.0, 8000.0]","(700, 1200]",0
3,"[2, 4)",CHRYSLER,PT CRUISER,LE,SILVER,Covers,"(80000, 100000]","(10000.0, 35722.0]",18822,TX,"(224.0, 5000.0]","(1200, 1800]",0
4,"[4, 6)",KIA,OPTIMA,EX,BLACK,Alloy,"(40000, 60000]","(3000.0, 6000.0]",20207,TX,"(5000.0, 7000.0]","(461, 700]",0

In [19]:
df['VehicleAge'] = 'Age:' + df['VehicleAge'].astype(str)
df['VehOdo'] = 'Odo:' + df['VehOdo'].astype(str)
df['AAAP'] = 'AAAP:' + df['AAAP'].astype(str)
df['WarrantyCost'] = 'WarrCost:' + df['WarrantyCost'].astype(str)
df['VehBCost'] = 'VehBCost:' + df['VehBCost'].astype(str)

df['BuyStatus'] = df['IsBadBuy'].map(
    {0: 'GoodBuy', 1: 'BadBuy'}).astype(str)
df.drop(columns=['IsBadBuy'], inplace=True)

In [20]:
df.head()

,VehicleAge,Make,Model,Trim,Color,WheelType,VehOdo,AAAP,BYRNO,VNST,VehBCost,WarrantyCost,BuyStatus
0,"Age:[4, 6)",KIA,SPECTRA,EX,GOLD,Covers,"Odo:(60000, 80000]","AAAP:(3000.0, 6000.0]",20740,NC,"VehBCost:(224.0, 5000.0]","WarrCost:(461, 700]",GoodBuy
1,"Age:[4, 6)",CHRYSLER,ION,Tou,SILVER,Covers,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",22808,TX,"VehBCost:(8000.0, 10000.0]","WarrCost:(1200, 1800]",GoodBuy
2,"Age:[2, 4)",MAZDA,MAZDA3,i,SILVER,Alloy,"Odo:(40000, 60000]","AAAP:(10000.0, 35722.0]",99761,NH,"VehBCost:(7000.0, 8000.0]","WarrCost:(700, 1200]",GoodBuy
3,"Age:[2, 4)",CHRYSLER,PT CRUISER,LE,SILVER,Covers,"Odo:(80000, 100000]","AAAP:(10000.0, 35722.0]",18822,TX,"VehBCost:(224.0, 5000.0]","WarrCost:(1200, 1800]",GoodBuy
4,"Age:[4, 6)",KIA,OPTIMA,EX,BLACK,Alloy,"Odo:(40000, 60000]","AAAP:(3000.0, 6000.0]",20207,TX,"VehBCost:(5000.0, 7000.0]","WarrCost:(461, 700]",GoodBuy

## APRIORI

In [21]:
from fim import apriori

In [22]:
baskets = df.values.tolist()

In [23]:
#supporto 2
itemsets = apriori(baskets, supp=11, zmin=3, target='a')

In [24]:
print('Number of itemsets:', len(itemsets))

Number of itemsets: 5

In [25]:
itemsets.sort(key=lambda x: x[1],reverse=True)

In [26]:
itemsets

[(('Odo:(60000, 80000]', 'Alloy', 'GoodBuy'), 1749),
 (('VehBCost:(5000.0, 7000.0]', 'Age:[4, 6)', 'AAAP:(3000.0, 6000.0]'), 1715),
 (('VehBCost:(5000.0, 7000.0]', 'AAAP:(3000.0, 6000.0]', 'BadBuy'), 1669),
 (('Age:[4, 6)', 'AAAP:(3000.0, 6000.0]', 'BadBuy'), 1666),
 (('Age:[4, 6)', 'Alloy', 'GoodBuy'), 1610)]

## Association Rules

In [27]:
rules = apriori(baskets, supp=11, zmin=3, target='r', conf=60, 
                report='ascl')

In [28]:
print('Number of rule:', len(rules))
rules[0]

Number of rule: 18

('BadBuy',
 ('VehBCost:(224.0, 5000.0]', 'AAAP:(3000.0, 6000.0]'),
 1039,
 0.0720826973775496,
 0.6133412042502951,
 1.2266824085005903)

In [29]:
rules.sort(key=lambda x: x[4],reverse=True)

In [30]:
count = 0
for r in rules:
    if r[5] > 0.60 and r[5]:
        print(r)
        count += 1
        if count == 10:
            break

('AAAP:(3000.0, 6000.0]', ('VehBCost:(5000.0, 7000.0]', 'Age:[4, 6)'), 1715, 0.11898154571943943, 0.7239341494301393, 1.7154014186891382)
('GoodBuy', ('AAAP:(6000.0, 8000.0]', 'Covers'), 1142, 0.07922852782017482, 0.7010435850214856, 1.4020871700429711)
('GoodBuy', ('Age:[2, 4)', 'Covers'), 1411, 0.09789093936450673, 0.686952288218111, 1.373904576436222)
('AAAP:(3000.0, 6000.0]', ('Covers', 'Age:[4, 6)'), 1394, 0.09671153045650062, 0.6498834498834499, 1.5399342506362068)
('GoodBuy', ('CHRYSLER', 'Covers'), 1340, 0.09296517274871653, 0.6479690522243714, 1.2959381044487428)
('GoodBuy', ('WarrCost:(700, 1200]', 'Covers'), 1365, 0.09469959761343139, 0.6438679245283019, 1.2877358490566038)
('AAAP:(3000.0, 6000.0]', ('VehBCost:(5000.0, 7000.0]', 'BadBuy'), 1669, 0.11579020396836409, 0.6321969696969697, 1.4980251719894988)
('GoodBuy', ('GM', 'Covers'), 1235, 0.08568058831691411, 0.6278596847991865, 1.255719369598373)
('GoodBuy', ('VehBCost:(5000.0, 7000.0]', 'Covers'), 1518, 0.10531427778548633, 0.6203514507560278, 1.2407029015120556)
('BadBuy', ('VehBCost:(224.0, 5000.0]', 'AAAP:(3000.0, 6000.0]'), 1039, 0.0720826973775496, 0.6133412042502951, 1.2266824085005903)

In [31]:
rules = apriori(baskets, supp=11, zmin=3, target='r', conf=70, 
                report='ascl')

In [32]:
rules.sort(key=lambda x: x[4],reverse=True)

In [33]:
count = 0
for r in rules:
    if r[5] > 0.70 and r[5]:
        print(r)
        count += 1
        if count == 10:
            break

('AAAP:(3000.0, 6000.0]', ('VehBCost:(5000.0, 7000.0]', 'Age:[4, 6)'), 1715, 0.11898154571943943, 0.7239341494301393, 1.7154014186891382)
('GoodBuy', ('AAAP:(6000.0, 8000.0]', 'Covers'), 1142, 0.07922852782017482, 0.7010435850214856, 1.4020871700429711)

In [34]:
df['Predicted'] = df['BuyStatus']

In [35]:
df['Predicted']  = np.where((np.logical_and(df['AAAP'] == 'AAAP:(6000.0, 8000.0]' ,df['WheelType'] == 'Covers')),str('GoodBuy'),str('BadBuy'))

In [36]:
df['Predicted']  = np.where((np.logical_and(df['VehicleAge'] == 'Age:[2, 4)' ,df['WheelType'] == 'Covers')),str('GoodBuy'),str('BadBuy'))

In [37]:
len(df['Predicted'])

14414

In [38]:
len(df['BuyStatus']) #OK!

14414

In [39]:
#DOVREBBE ESSERE IL NUMERO TOTALE DI TRUE POSITIVE E TRUE NEGATIVE
len(df[df.Predicted == df.BuyStatus])

7975

In [40]:
#DOVREBBE ESSERE IL NUMERO TOTALE DI FALSE POSITIVE E FALSE NEGATIVE

len(df[df.Predicted != df.BuyStatus])

6439

In [41]:
#Accuratezza = TP+TN/TP+TN+FP+FN

7975/(7975+6439)

0.5532815318440405

PROVA MALEDETTO LOWRENZO CHE OVVIAMENTE E' LA MIGLIORE

In [42]:
df['PredictionLore'] = "NotPredicted"

In [43]:
#('GoodBuy', ('AAAP:(6000.0, 8000.0]', 'Covers'), 1142, 0.07922852782017482, 0.7010435850214856, 1.4020871700429711)
df['PredictionLore']  = np.where((np.logical_and(df['AAAP'] == 'AAAP:(6000.0, 8000.0]' ,df['WheelType'] == 'Covers')),str('GoodBuy'),df['PredictionLore'] )

In [44]:
#('GoodBuy', ('Age:[2, 4)', 'Covers'), 1411, 0.09789093936450673, 0.686952288218111, 1.373904576436222)
df['PredictionLore']  = np.where((np.logical_and(df['VehicleAge'] == 'Age:[2, 4)' ,df['WheelType'] == 'Covers')),str('GoodBuy'),df['PredictionLore'])

In [45]:
#('GoodBuy', ('CHRYSLER', 'Covers'), 1340, 0.09296517274871653, 0.6479690522243714, 1.2959381044487428)
df['PredictionLore']  = np.where(np.logical_and(df['Make'] == 'CHRYSLER' ,df['WheelType'] == 'Covers'),str('GoodBuy'),df['PredictionLore'])

In [46]:
#('BadBuy', ('VehBCost:(224.0, 5000.0]', 'AAAP:(3000.0, 6000.0]'), 1039, 0.0720826973775496, 0.6133412042502951, 1.2266824085005903)
ppp = np.logical_and(df['VehBCost'] == 'VehBCost:(224.0, 5000.0]' ,df['AAAP'] == 'AAAP:(3000.0, 6000.0]')
df['PredictionLore']  = np.where(np.logical_and(ppp, df['PredictionLore'] == 'NotPredicted'),str('BadBuy'),df['PredictionLore'])

In [47]:
len(df[df['PredictionLore'] != 'NotPredicted'])

5123

In [48]:
df_temp = df[df['PredictionLore'] != 'NotPredicted']
type(df_temp)

pandas.core.frame.DataFrame

In [49]:
df_temp[df_temp['PredictionLore'] == df_temp['BuyStatus']]

,VehicleAge,Make,Model,Trim,Color,WheelType,VehOdo,AAAP,BYRNO,VNST,VehBCost,WarrantyCost,BuyStatus,Predicted,PredictionLore
1,"Age:[4, 6)",CHRYSLER,ION,Tou,SILVER,Covers,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",22808,TX,"VehBCost:(8000.0, 10000.0]","WarrCost:(1200, 1800]",GoodBuy,BadBuy,GoodBuy
3,"Age:[2, 4)",CHRYSLER,PT CRUISER,LE,SILVER,Covers,"Odo:(80000, 100000]","AAAP:(10000.0, 35722.0]",18822,TX,"VehBCost:(224.0, 5000.0]","WarrCost:(1200, 1800]",GoodBuy,GoodBuy,GoodBuy
5,"Age:[0, 2)",CHRYSLER,AVENGER,SE,SILVER,Covers,"Odo:(40000, 60000]","AAAP:(6000.0, 8000.0]",99761,AZ,"VehBCost:(7000.0, 8000.0]","WarrCost:(700, 1200]",GoodBuy,BadBuy,GoodBuy
7,"Age:[2, 4)",GM,IMPALA,LS,GREY,Covers,"Odo:(40000, 60000]","AAAP:(8000.0, 10000.0]",99750,MD,"VehBCost:(7000.0, 8000.0]","WarrCost:(1200, 1800]",GoodBuy,GoodBuy,GoodBuy
11,"Age:[2, 4)",FORD,TRAILBLAZER,LS,WHITE,Covers,"Odo:(40000, 60000]","AAAP:(6000.0, 8000.0]",20833,TX,"VehBCost:(5000.0, 7000.0]","WarrCost:(700, 1200]",GoodBuy,GoodBuy,GoodBuy
14,"Age:[2, 4)",CHRYSLER,SEBRING,Bas,BLACK,Covers,"Odo:(40000, 60000]","AAAP:(6000.0, 8000.0]",99750,NJ,"VehBCost:(7000.0, 8000.0]","WarrCost:(700, 1200]",GoodBuy,GoodBuy,GoodBuy
16,"Age:[2, 4)",CHRYSLER,CHARGER,Bas,GREY,Covers,"Odo:(60000, 80000]","AAAP:(10000.0, 35722.0]",52644,TX,"VehBCost:(8000.0, 10000.0]","WarrCost:(1200, 1800]",GoodBuy,GoodBuy,GoodBuy
19,"Age:[4, 6)",GM,VIBE,Bas,WHITE,Covers,"Odo:(60000, 80000]","AAAP:(6000.0, 8000.0]",10315,FL,"VehBCost:(8000.0, 10000.0]","WarrCost:(461, 700]",GoodBuy,BadBuy,GoodBuy
25,"Age:[2, 4)",NISSAN,ALTIMA,Bas,WHITE,Covers,"Odo:(60000, 80000]","AAAP:(10000.0, 35722.0]",20740,SC,"VehBCost:(10000.0, 36485.0]","WarrCost:(461, 700]",GoodBuy,GoodBuy,GoodBuy
29,"Age:[2, 4)",GM,ION,LT,BLACK,Covers,"Odo:(60000, 80000]","AAAP:(6000.0, 8000.0]",20234,AZ,"VehBCost:(5000.0, 7000.0]","WarrCost:(700, 1200]",GoodBuy,GoodBuy,GoodBuy
30,"Age:[2, 4)",CHRYSLER,STRATUS,SXT,GREY,Covers,"Odo:(60000, 80000]","AAAP:(3000.0, 6000.0]",20234,AZ,"VehBCost:(224.0, 5000.0]","WarrCost:(1200, 1800]",GoodBuy,GoodBuy,GoodBuy
39,"Age:[2, 4)",CHRYSLER,CALIBER,SXT,BEIGE,Covers,"Odo:(60000, 80000]","AAAP:(6000.0, 8000.0]",8172,TN,"VehBCost:(5000.0, 7000.0]","WarrCost:(700, 1200]",GoodBuy,GoodBuy,GoodBuy
46,"Age:[6, 8)",GM,MALIBU,150,RED,Covers,"Odo:(60000, 80000]","AAAP:(6000.0, 8000.0]",22916,NV,"VehBCost:(7000.0, 8000.0]","WarrCost:(461, 700]",GoodBuy,BadBuy,GoodBuy
49,"Age:[6, 8)",CHRYSLER,CHARGER,CX,GREY,Covers,"Odo:(60000, 80000]","AAAP:(3000.0, 6000.0]",21973,FL,"VehBCost:(5000.0, 7000.0]","WarrCost:(1200, 1800]",GoodBuy,BadBuy,GoodBuy
50,"Age:[2, 4)",HYUNDAI,CALIBER,Bas,BLACK,Covers,"Odo:(60000, 80000]","AAAP:(8000.0, 10000.0]",20928,FL,"VehBCost:(224.0, 5000.0]","WarrCost:(700, 1200]",GoodBuy,GoodBuy,GoodBuy
51,"Age:[2, 4)",CHRYSLER,STRATUS,SXT,BLUE,Covers,"Odo:(60000, 80000]","AAAP:(3000.0, 6000.0]",99750,MS,"VehBCost:(224.0, 5000.0]","WarrCost:(1200, 1800]",GoodBuy,GoodBuy,GoodBuy
57,"Age:[2, 4)",CHRYSLER,SEBRING,LX,BLUE,Covers,"Odo:(40000, 60000]","AAAP:(8000.0, 10000.0]",99761,OK,"VehBCost:(8000.0, 10000.0]","WarrCost:(700, 1200]",GoodBuy,GoodBuy,GoodBuy
58,"Age:[2, 4)",CHRYSLER,ELANTRA,Bas,BLUE,Covers,"Odo:(60000, 80000]","AAAP:(3000.0, 6000.0]",20928,OH,"VehBCost:(7000.0, 8000.0]","WarrCost:(1200, 1800]",GoodBuy,GoodBuy,GoodBuy
60,"Age:[4, 6)",GM,IMPALA,LS,GREY,Covers,"Odo:(60000, 80000]","AAAP:(6000.0, 8000.0]",20928,FL,"VehBCost:(7000.0, 8000.0]","WarrCost:(1800, 2600]",GoodBuy,BadBuy,GoodBuy
64,"Age:[0, 2)",CHRYSLER,AVENGER,SE,GREY,Covers,"Odo:(60000, 80000]","AAAP:(6000.0, 8000.0]",18111,GA,"VehBCost:(7000.0, 8000.0]","WarrCost:(700, 1200]",GoodBuy,BadBuy,GoodBuy
74,"Age:[6, 8)",CHRYSLER,CARAVAN,Spo,SILVER,Covers,"Odo:(80000, 100000]","AAAP:(-1143.969, 3000.0]",19638,FL,"VehBCost:(224.0, 5000.0]","WarrCost:(1800, 2600]",GoodBuy,BadBuy,GoodBuy
79,"Age:[2, 4)",GM,COBALT,LS,BLACK,Covers,"Odo:(40000, 60000]","AAAP:(3000.0, 6000.0]",20833,IL,"VehBCost:(5000.0, 7000.0]","WarrCost:(461, 700]",GoodBuy,GoodBuy,GoodBuy
84,"Age:[6, 8)",CHRYSLER,CARAVAN,SE,BLUE,Covers,"Odo:(80000, 100000]","AAAP:(-1143.969, 3000.0]",835,AZ,"VehBCost:(224.0, 5000.0]","WarrCost:(1800, 2600]",GoodBuy,BadBuy,GoodBuy
86,"Age:[2, 4)",GM,UPLANDER,LS,BLUE,Covers,"Odo:(80000, 100000]","AAAP:(6000.0, 8000.0]",17675,NC,"VehBCost:(5000.0, 7000.0]","WarrCost:(1800, 2600]",GoodBuy,GoodBuy,GoodBuy
90,"Age:[2, 4)",GM,ION,2,GREY,Covers,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",19638,AL,"VehBCost:(5000.0, 7000.0]","WarrCost:(700, 1200]",GoodBuy,GoodBuy,GoodBuy
95,"Age:[6, 8)",CHRYSLER,IMPALA,SE,WHITE,Covers,"Odo:(60000, 80000]","AAAP:(-1143.969, 3000.0]",52117,OH,"VehBCost:(5000.0, 7000.0]","WarrCost:(1200, 1800]",GoodBuy,BadBuy,GoodBuy
97,"Age:[2, 4)",GM,VENTURE,Lim,BLUE,Covers,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",18111,KY,"VehBCost:(7000.0, 8000.0]","WarrCost:(1800, 2600]",GoodBuy,GoodBuy,GoodBuy
112,"Age:[2, 4)",GM,HHR,LS,GOLD,Covers,"Odo:(80000, 100000]","AAAP:(6000.0, 8000.0]",20740,NC,"VehBCost:(5000.0, 7000.0]","WarrCost:(700, 1200]",GoodBuy,GoodBuy,GoodBuy
113,"Age:[2, 4)",GM,IMPALA,LS,SILVER,Covers,"Odo:(60000, 80000]","AAAP:(6000.0, 8000.0]",8655,TX,"VehBCost:(8000.0, 10000.0]","WarrCost:(1800, 2600]",GoodBuy,GoodBuy,GoodBuy
114,"Age:[6, 8)",CHRYSLER,PT CRUISER,Bas,GOLD,Covers,"Odo:(60000, 80000]","AAAP:(3000.0, 6000.0]",22916,CO,"VehBCost:(224.0, 5000.0]","WarrCost:(1200, 1800]",GoodBuy,BadBuy,GoodBuy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14089,"Age:[4, 6)",FORD,COBALT,ES,GREY,Covers,"Odo:(60000, 80000]","AAAP:(3000.0, 6000.0]",20207,TX,"VehBCost:(224.0, 5000.0]","WarrCost:(700, 1200]",BadBuy,BadBuy,BadBuy
14103,"Age:[4, 6)",CHRYSLER,FORENZA,-8.736686370643817,SILVER,Alloy,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",18880,SC,"VehBCost:(224.0, 5000.0]","WarrCost:(1200, 1800]",BadBuy,BadBuy,BadBuy
14118,"Age:[4, 6)",FORD,SEBRING,LS,GREY,Alloy,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",18822,TX,"VehBCost:(224.0, 5000.0]","WarrCost:(1800, 2600]",BadBuy,BadBuy,BadBuy
14126,"Age:[4, 6)",FORD,LIBERTY,GLS,GREY,Alloy,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",8655,TX,"VehBCost:(224.0, 5000.0]","WarrCost:(700, 1200]",BadBuy,BadBuy,BadBuy
14139,"Age:[4, 6)",CHRYSLER,FORENZA,Bas,SILVER,Alloy,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",3453,CO,"VehBCost:(224.0, 5000.0]","WarrCost:(1800, 2600]",BadBuy,BadBuy,BadBuy
14157,"Age:[2, 4)",FORD,CAVALIER,LS,RED,Alloy,"Odo:(100000, 115717]","AAAP:(3000.0, 6000.0]",18880,GA,"VehBCost:(224.0, 5000.0]","WarrCost:(700, 1200]",BadBuy,BadBuy,BadBuy
14162,"Age:[4, 6)",FORD,STRATUS,SXT,WHITE,Alloy,"Odo:(60000, 80000]","AAAP:(3000.0, 6000.0]",16926,CA,"VehBCost:(224.0, 5000.0]","WarrCost:(1200, 1800]",BadBuy,BadBuy,BadBuy
14176,"Age:[4, 6)",GM,TAURUS,-61.129947579963016,SILVER,Alloy,"Odo:(40000, 60000]","AAAP:(3000.0, 6000.0]",17675,VA,"VehBCost:(224.0, 5000.0]","WarrCost:(1200, 1800]",BadBuy,BadBuy,BadBuy
14191,"Age:[4, 6)",FORD,TRAILBLAZER,SXT,WHITE,UNKNOWN,"Odo:(100000, 115717]","AAAP:(3000.0, 6000.0]",18822,TX,"VehBCost:(224.0, 5000.0]","WarrCost:(1200, 1800]",BadBuy,BadBuy,BadBuy
14203,"Age:[8, 10)",FORD,1500 SILVERADO,ST,BLACK,UNKNOWN,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",25100,TX,"VehBCost:(224.0, 5000.0]","WarrCost:(700, 1200]",BadBuy,BadBuy,BadBuy
14214,"Age:[4, 6)",FORD,FOCUS,1,BLACK,Covers,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",52492,NC,"VehBCost:(224.0, 5000.0]","WarrCost:(1200, 1800]",BadBuy,BadBuy,BadBuy
14215,"Age:[6, 8)",CHRYSLER,FREESTAR,Bas,BLUE,UNKNOWN,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",21053,NM,"VehBCost:(224.0, 5000.0]","WarrCost:(1200, 1800]",BadBuy,BadBuy,BadBuy
14235,"Age:[6, 8)",GM,GALANT,LS,GREEN,Alloy,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",25100,TX,"VehBCost:(224.0, 5000.0]","WarrCost:(2600, 6819]",BadBuy,BadBuy,BadBuy
14236,"Age:[6, 8)",FORD,SENTRA,XLS,WHITE,Alloy,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",19619,FL,"VehBCost:(224.0, 5000.0]","WarrCost:(1200, 1800]",BadBuy,BadBuy,BadBuy
14238,"Age:[4, 6)",GM,1500 RAM PICKUP,S,GOLD,Covers,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",835,AZ,"VehBCost:(224.0, 5000.0]","WarrCost:(1800, 2600]",BadBuy,BadBuy,BadBuy
14239,"Age:[4, 6)",FORD,STRATUS,3,SILVER,Alloy,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",8655,TX,"VehBCost:(224.0, 5000.0]","WarrCost:(700, 1200]",BadBuy,BadBuy,BadBuy
14247,"Age:[2, 4)",FORD,MALIBU,SXT,WHITE,Alloy,"Odo:(60000, 80000]","AAAP:(3000.0, 6000.0]",23359,CA,"VehBCost:(224.0, 5000.0]","WarrCost:(700, 1200]",BadBuy,BadBuy,BadBuy
14261,"Age:[6, 8)",SUZUKI,COBALT,GT,ORANGE,Covers,"Odo:(60000, 80000]","AAAP:(3000.0, 6000.0]",835,AZ,"VehBCost:(224.0, 5000.0]","WarrCost:(461, 700]",BadBuy,BadBuy,BadBuy
14285,"Age:[4, 6)",FORD,RIO,LS,PURPLE,Covers,"Odo:(60000, 80000]","AAAP:(3000.0, 6000.0]",20740,MD,"VehBCost:(224.0, 5000.0]","WarrCost:(700, 1200]",BadBuy,BadBuy,BadBuy
14291,"Age:[4, 6)",FORD,1500 RAM PICKUP,Bas,GOLD,Covers,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",22808,OK,"VehBCost:(224.0, 5000.0]","WarrCost:(1200, 1800]",BadBuy,BadBuy,BadBuy
14297,"Age:[6, 8)",GM,TAURUS,Bas,SILVER,Covers,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",23359,CA,"VehBCost:(224.0, 5000.0]","WarrCost:(1800, 2600]",BadBuy,BadBuy,BadBuy
14305,"Age:[6, 8)",FORD,GRAND PRIX,Cus,GOLD,Alloy,"Odo:(40000, 60000]","AAAP:(3000.0, 6000.0]",16926,CA,"VehBCost:(224.0, 5000.0]","WarrCost:(700, 1200]",BadBuy,BadBuy,BadBuy
14306,"Age:[8, 10)",FORD,CARAVAN GRAND,Bas,BLUE,Alloy,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",22808,TX,"VehBCost:(224.0, 5000.0]","WarrCost:(461, 700]",BadBuy,BadBuy,BadBuy
14310,"Age:[2, 4)",GM,EQUINOX,SE,WHITE,Alloy,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",21973,FL,"VehBCost:(224.0, 5000.0]","WarrCost:(1800, 2600]",BadBuy,BadBuy,BadBuy
14313,"Age:[2, 4)",GM,PT CRUISER,SE,BLUE,Alloy,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",20928,NC,"VehBCost:(224.0, 5000.0]","WarrCost:(2600, 6819]",BadBuy,BadBuy,BadBuy
14335,"Age:[6, 8)",GM,SENTRA,GT,RED,Covers,"Odo:(60000, 80000]","AAAP:(3000.0, 6000.0]",8655,MO,"VehBCost:(224.0, 5000.0]","WarrCost:(1200, 1800]",BadBuy,BadBuy,BadBuy
14346,"Age:[6, 8)",FORD,CARAVAN GRAND,ES,GOLD,Alloy,"Odo:(60000, 80000]","AAAP:(3000.0, 6000.0]",20833,TX,"VehBCost:(224.0, 5000.0]","WarrCost:(1800, 2600]",BadBuy,BadBuy,BadBuy
14363,"Age:[6, 8)",HYUNDAI,SEBRING,CE,SILVER,Covers,"Odo:(60000, 80000]","AAAP:(3000.0, 6000.0]",19619,FL,"VehBCost:(224.0, 5000.0]","WarrCost:(1200, 1800]",BadBuy,BadBuy,BadBuy
14372,"Age:[6, 8)",CHRYSLER,TIBURON,Spo,MAROON,Alloy,"Odo:(60000, 80000]","AAAP:(3000.0, 6000.0]",16926,CA,"VehBCost:(224.0, 5000.0]","WarrCost:(1800, 2600]",BadBuy,BadBuy,BadBuy
14382,"Age:[4, 6)",GM,TOWN & COUNTRY V,SLT,GREY,UNKNOWN,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",16926,CA,"VehBCost:(224.0, 5000.0]","WarrCost:(1200, 1800]",BadBuy,BadBuy,BadBuy

In [50]:
len(df_temp[df_temp['PredictionLore'] == df_temp['BuyStatus']])

3366

In [51]:
len(df_temp[df_temp.PredictionLore == df_temp.BuyStatus])

3366

In [52]:
len(df_temp[df_temp.PredictionLore != df_temp.BuyStatus])

1757

In [53]:
1876/(848+1876)

0.6886930983847284

In [54]:
#Nuova accuratezza schifo 
2844/(2844+1457)

0.6612415717275052

In [55]:
3366/(1757+3366)

0.6570368924458325

In [56]:
df_temp[df_temp['PredictionLore'] != df_temp['BuyStatus']]

,VehicleAge,Make,Model,Trim,Color,WheelType,VehOdo,AAAP,BYRNO,VNST,VehBCost,WarrantyCost,BuyStatus,Predicted,PredictionLore
0,"Age:[4, 6)",KIA,SPECTRA,EX,GOLD,Covers,"Odo:(60000, 80000]","AAAP:(3000.0, 6000.0]",20740,NC,"VehBCost:(224.0, 5000.0]","WarrCost:(461, 700]",GoodBuy,BadBuy,BadBuy
13,"Age:[4, 6)",GM,ENDEAVOR,SE,PURPLE,Covers,"Odo:(60000, 80000]","AAAP:(3000.0, 6000.0]",21053,CA,"VehBCost:(224.0, 5000.0]","WarrCost:(700, 1200]",GoodBuy,BadBuy,BadBuy
21,"Age:[4, 6)",CHRYSLER,STRATUS,SXT,WHITE,Alloy,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",835,AZ,"VehBCost:(224.0, 5000.0]","WarrCost:(1200, 1800]",GoodBuy,BadBuy,BadBuy
26,"Age:[4, 6)",CHRYSLER,NEON,SXT,BLACK,Alloy,"Odo:(60000, 80000]","AAAP:(3000.0, 6000.0]",18111,TN,"VehBCost:(224.0, 5000.0]","WarrCost:(461, 700]",GoodBuy,BadBuy,BadBuy
55,"Age:[4, 6)",GM,GRAND PRIX,Bas,GOLD,Covers,"Odo:(4824, 40000]","AAAP:(3000.0, 6000.0]",835,AZ,"VehBCost:(224.0, 5000.0]","WarrCost:(461, 700]",GoodBuy,BadBuy,BadBuy
65,"Age:[4, 6)",GM,FOCUS,SXT,WHITE,Alloy,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",20928,FL,"VehBCost:(224.0, 5000.0]","WarrCost:(1800, 2600]",GoodBuy,BadBuy,BadBuy
91,"Age:[4, 6)",FORD,FOCUS,ZX5,SILVER,Alloy,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",52598,TX,"VehBCost:(224.0, 5000.0]","WarrCost:(1200, 1800]",GoodBuy,BadBuy,BadBuy
105,"Age:[6, 8)",GM,CHARGER,Tou,GOLD,Covers,"Odo:(60000, 80000]","AAAP:(3000.0, 6000.0]",19619,FL,"VehBCost:(224.0, 5000.0]","WarrCost:(1200, 1800]",GoodBuy,BadBuy,BadBuy
108,"Age:[6, 8)",GM,ION,2,BLACK,Covers,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",22808,TN,"VehBCost:(224.0, 5000.0]","WarrCost:(700, 1200]",GoodBuy,BadBuy,BadBuy
138,"Age:[6, 8)",NISSAN,SENTRA,S,GREY,Covers,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",1151,CA,"VehBCost:(224.0, 5000.0]","WarrCost:(461, 700]",GoodBuy,BadBuy,BadBuy
141,"Age:[6, 8)",GM,MONTANA,-36.39520241368026,GOLD,Alloy,"Odo:(60000, 80000]","AAAP:(3000.0, 6000.0]",21973,FL,"VehBCost:(224.0, 5000.0]","WarrCost:(2600, 6819]",GoodBuy,BadBuy,BadBuy
166,"Age:[4, 6)",GM,IMPALA,Tou,GREY,Covers,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",21053,CA,"VehBCost:(224.0, 5000.0]","WarrCost:(1800, 2600]",GoodBuy,BadBuy,BadBuy
167,"Age:[4, 6)",GM,MALIBU,Cla,SILVER,Alloy,"Odo:(100000, 115717]","AAAP:(3000.0, 6000.0]",22916,CO,"VehBCost:(224.0, 5000.0]","WarrCost:(1200, 1800]",GoodBuy,BadBuy,BadBuy
179,"Age:[4, 6)",CHRYSLER,STRATUS,SXT,SILVER,Alloy,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",17675,NC,"VehBCost:(224.0, 5000.0]","WarrCost:(1200, 1800]",GoodBuy,BadBuy,BadBuy
189,"Age:[6, 8)",GM,ION,3,GREEN,Alloy,"Odo:(40000, 60000]","AAAP:(3000.0, 6000.0]",21973,FL,"VehBCost:(224.0, 5000.0]","WarrCost:(461, 700]",GoodBuy,BadBuy,BadBuy
193,"Age:[4, 6)",KIA,OPTIMA,EX,WHITE,Covers,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",20928,FL,"VehBCost:(224.0, 5000.0]","WarrCost:(700, 1200]",GoodBuy,BadBuy,BadBuy
205,"Age:[4, 6)",GM,MALIBU,2,GREY,Alloy,"Odo:(40000, 60000]","AAAP:(3000.0, 6000.0]",17675,NC,"VehBCost:(224.0, 5000.0]","WarrCost:(461, 700]",GoodBuy,BadBuy,BadBuy
257,"Age:[6, 8)",CHRYSLER,PT CRUISER,Tou,GOLD,Alloy,"Odo:(40000, 60000]","AAAP:(3000.0, 6000.0]",21973,FL,"VehBCost:(224.0, 5000.0]","WarrCost:(1200, 1800]",GoodBuy,BadBuy,BadBuy
259,"Age:[4, 6)",GM,GRAND PRIX,Bas,SILVER,Covers,"Odo:(100000, 115717]","AAAP:(3000.0, 6000.0]",835,AZ,"VehBCost:(224.0, 5000.0]","WarrCost:(1800, 2600]",GoodBuy,BadBuy,BadBuy
263,"Age:[4, 6)",CHRYSLER,DAKOTA PICKUP,Bas,WHITE,UNKNOWN,"Odo:(60000, 80000]","AAAP:(3000.0, 6000.0]",20928,TN,"VehBCost:(224.0, 5000.0]","WarrCost:(1200, 1800]",GoodBuy,BadBuy,BadBuy
264,"Age:[4, 6)",GM,ION,2,GREY,Covers,"Odo:(60000, 80000]","AAAP:(3000.0, 6000.0]",5546,FL,"VehBCost:(224.0, 5000.0]","WarrCost:(700, 1200]",GoodBuy,BadBuy,BadBuy
278,"Age:[6, 8)",HYUNDAI,SONATA,GLS,WHITE,Alloy,"Odo:(40000, 60000]","AAAP:(3000.0, 6000.0]",18111,TN,"VehBCost:(224.0, 5000.0]","WarrCost:(700, 1200]",GoodBuy,BadBuy,BadBuy
302,"Age:[4, 6)",KIA,MAZDA5,Tou,GREEN,Alloy,"Odo:(60000, 80000]","AAAP:(3000.0, 6000.0]",17212,OK,"VehBCost:(224.0, 5000.0]","WarrCost:(700, 1200]",GoodBuy,BadBuy,BadBuy
314,"Age:[6, 8)",GM,MALIBU,Cla,SILVER,Alloy,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",8655,TX,"VehBCost:(224.0, 5000.0]","WarrCost:(1200, 1800]",GoodBuy,BadBuy,BadBuy
338,"Age:[6, 8)",GM,ION,2,GREY,Covers,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",20833,TX,"VehBCost:(224.0, 5000.0]","WarrCost:(700, 1200]",GoodBuy,BadBuy,BadBuy
341,"Age:[4, 6)",KIA,RIO,Bas,SILVER,Covers,"Odo:(60000, 80000]","AAAP:(3000.0, 6000.0]",1235,CO,"VehBCost:(224.0, 5000.0]","WarrCost:(461, 700]",GoodBuy,BadBuy,BadBuy
354,"Age:[6, 8)",FORD,TAURUS,SE,MAROON,Covers,"Odo:(60000, 80000]","AAAP:(3000.0, 6000.0]",18880,TN,"VehBCost:(224.0, 5000.0]","WarrCost:(700, 1200]",GoodBuy,BadBuy,BadBuy
370,"Age:[6, 8)",GM,MALIBU,LS,WHITE,Alloy,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",52492,SC,"VehBCost:(224.0, 5000.0]","WarrCost:(2600, 6819]",GoodBuy,BadBuy,BadBuy
384,"Age:[6, 8)",FORD,FOCUS,ZX5,SILVER,Alloy,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",18111,GA,"VehBCost:(224.0, 5000.0]","WarrCost:(1200, 1800]",GoodBuy,BadBuy,BadBuy
393,"Age:[4, 6)",GM,ALERO,GL,WHITE,Covers,"Odo:(60000, 80000]","AAAP:(3000.0, 6000.0]",22916,CO,"VehBCost:(224.0, 5000.0]","WarrCost:(1200, 1800]",GoodBuy,BadBuy,BadBuy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14241,"Age:[2, 4)",CHRYSLER,CAVALIER,ES,SILVER,Covers,"Odo:(60000, 80000]","AAAP:(6000.0, 8000.0]",22916,CO,"VehBCost:(5000.0, 7000.0]","WarrCost:(1200, 1800]",BadBuy,GoodBuy,GoodBuy
14248,"Age:[2, 4)",GM,VUE,SE,WHITE,Covers,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",18880,SC,"VehBCost:(8000.0, 10000.0]","WarrCost:(1200, 1800]",BadBuy,GoodBuy,GoodBuy
14263,"Age:[2, 4)",GM,1500 SILVERADO,SEL,WHITE,Covers,"Odo:(40000, 60000]","AAAP:(10000.0, 35722.0]",20833,TX,"VehBCost:(5000.0, 7000.0]","WarrCost:(461, 700]",BadBuy,GoodBuy,GoodBuy
14265,"Age:[4, 6)",CHRYSLER,SEBRING,s,BLUE,Covers,"Odo:(40000, 60000]","AAAP:(3000.0, 6000.0]",99761,CA,"VehBCost:(5000.0, 7000.0]","WarrCost:(700, 1200]",BadBuy,BadBuy,GoodBuy
14268,"Age:[2, 4)",CHRYSLER,COMPASS,56.81609161444976,GREY,Covers,"Odo:(60000, 80000]","AAAP:(10000.0, 35722.0]",835,AZ,"VehBCost:(10000.0, 36485.0]","WarrCost:(461, 700]",BadBuy,GoodBuy,GoodBuy
14279,"Age:[2, 4)",GM,MALIBU,Spo,BLACK,Covers,"Odo:(60000, 80000]","AAAP:(8000.0, 10000.0]",20740,SC,"VehBCost:(5000.0, 7000.0]","WarrCost:(700, 1200]",BadBuy,GoodBuy,GoodBuy
14283,"Age:[2, 4)",CHRYSLER,TAURUS,LT,BLUE,Covers,"Odo:(80000, 100000]","AAAP:(6000.0, 8000.0]",52117,VA,"VehBCost:(224.0, 5000.0]","WarrCost:(1200, 1800]",BadBuy,GoodBuy,GoodBuy
14290,"Age:[6, 8)",CHRYSLER,LE SABRE,GS,WHITE,Covers,"Odo:(60000, 80000]","AAAP:(-1143.969, 3000.0]",21053,AZ,"VehBCost:(5000.0, 7000.0]","WarrCost:(1200, 1800]",BadBuy,BadBuy,GoodBuy
14293,"Age:[4, 6)",CHRYSLER,PT CRUISER,LS,BLUE,Covers,"Odo:(80000, 100000]","AAAP:(8000.0, 10000.0]",20740,VA,"VehBCost:(8000.0, 10000.0]","WarrCost:(1800, 2600]",BadBuy,BadBuy,GoodBuy
14295,"Age:[6, 8)",CHRYSLER,TOWN & COUNTRY V,SE,WHITE,Covers,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",835,AZ,"VehBCost:(5000.0, 7000.0]","WarrCost:(1800, 2600]",BadBuy,BadBuy,GoodBuy
14301,"Age:[2, 4)",CHRYSLER,PT CRUISER,SE,ORANGE,Covers,"Odo:(40000, 60000]","AAAP:(6000.0, 8000.0]",18822,TX,"VehBCost:(5000.0, 7000.0]","WarrCost:(700, 1200]",BadBuy,GoodBuy,GoodBuy
14302,"Age:[2, 4)",CHRYSLER,XB,LS,WHITE,Covers,"Odo:(40000, 60000]","AAAP:(6000.0, 8000.0]",99761,OK,"VehBCost:(7000.0, 8000.0]","WarrCost:(700, 1200]",BadBuy,GoodBuy,GoodBuy
14304,"Age:[4, 6)",CHRYSLER,COROLLA,Bas,SILVER,Covers,"Odo:(60000, 80000]","AAAP:(6000.0, 8000.0]",20833,OK,"VehBCost:(5000.0, 7000.0]","WarrCost:(1200, 1800]",BadBuy,BadBuy,GoodBuy
14308,"Age:[4, 6)",CHRYSLER,IMPALA,LS,GOLD,Covers,"Odo:(60000, 80000]","AAAP:(3000.0, 6000.0]",20928,FL,"VehBCost:(5000.0, 7000.0]","WarrCost:(1200, 1800]",BadBuy,BadBuy,GoodBuy
14311,"Age:[2, 4)",FORD,TAURUS,SEL,SILVER,Covers,"Odo:(80000, 100000]","AAAP:(10000.0, 35722.0]",8655,TX,"VehBCost:(224.0, 5000.0]","WarrCost:(1200, 1800]",BadBuy,GoodBuy,GoodBuy
14324,"Age:[6, 8)",KIA,GRAND CHEROKEE,94.21441846378762,SILVER,Covers,"Odo:(80000, 100000]","AAAP:(6000.0, 8000.0]",20740,SC,"VehBCost:(224.0, 5000.0]","WarrCost:(700, 1200]",BadBuy,BadBuy,GoodBuy
14338,"Age:[2, 4)",CHRYSLER,TRAILBLAZER,LT,RED,Covers,"Odo:(80000, 100000]","AAAP:(8000.0, 10000.0]",835,AZ,"VehBCost:(7000.0, 8000.0]","WarrCost:(700, 1200]",BadBuy,GoodBuy,GoodBuy
14340,"Age:[2, 4)",TOYOTA,TUNDRA PICKUP,Bas,SILVER,Covers,"Odo:(60000, 80000]","AAAP:(8000.0, 10000.0]",18880,SC,"VehBCost:(10000.0, 36485.0]","WarrCost:(461, 700]",BadBuy,GoodBuy,GoodBuy
14342,"Age:[4, 6)",CHRYSLER,ION,SXT,SILVER,Covers,"Odo:(60000, 80000]","AAAP:(3000.0, 6000.0]",835,AZ,"VehBCost:(8000.0, 10000.0]","WarrCost:(700, 1200]",BadBuy,BadBuy,GoodBuy
14364,"Age:[4, 6)",CHRYSLER,MALIBU,SXT,BLUE,Covers,"Odo:(60000, 80000]","AAAP:(3000.0, 6000.0]",52492,SC,"VehBCost:(5000.0, 7000.0]","WarrCost:(461, 700]",BadBuy,BadBuy,GoodBuy
14370,"Age:[2, 4)",GM,CAVALIER,EX,SILVER,Covers,"Odo:(80000, 100000]","AAAP:(6000.0, 8000.0]",18880,SC,"VehBCost:(5000.0, 7000.0]","WarrCost:(2600, 6819]",BadBuy,GoodBuy,GoodBuy
14380,"Age:[2, 4)",TOYOTA,FORENZA,Bas,RED,Covers,"Odo:(80000, 100000]","AAAP:(8000.0, 10000.0]",22808,TX,"VehBCost:(5000.0, 7000.0]","WarrCost:(461, 700]",BadBuy,GoodBuy,GoodBuy
14391,"Age:[4, 6)",GM,FOCUS,Tou,GOLD,Covers,"Odo:(60000, 80000]","AAAP:(6000.0, 8000.0]",21973,FL,"VehBCost:(5000.0, 7000.0]","WarrCost:(1800, 2600]",BadBuy,BadBuy,GoodBuy
14392,"Age:[2, 4)",NISSAN,MUSTANG,Lim,SILVER,Covers,"Odo:(80000, 100000]","AAAP:(10000.0, 35722.0]",20928,NC,"VehBCost:(5000.0, 7000.0]","WarrCost:(700, 1200]",BadBuy,GoodBuy,GoodBuy
14393,"Age:[2, 4)",CHRYSLER,LIBERTY,LS,BEIGE,Covers,"Odo:(40000, 60000]","AAAP:(6000.0, 8000.0]",99761,OK,"VehBCost:(7000.0, 8000.0]","WarrCost:(700, 1200]",BadBuy,GoodBuy,GoodBuy
14397,"Age:[4, 6)",CHRYSLER,1500 SILVERADO,SE,BLUE,Covers,"Odo:(80000, 100000]","AAAP:(6000.0, 8000.0]",18880,GA,"VehBCost:(5000.0, 7000.0]","WarrCost:(1200, 1800]",BadBuy,BadBuy,GoodBuy
14399,"Age:[0, 2)",FORD,G6,SE,SILVER,Covers,"Odo:(60000, 80000]","AAAP:(6000.0, 8000.0]",21053,AZ,"VehBCost:(7000.0, 8000.0]","WarrCost:(700, 1200]",BadBuy,BadBuy,GoodBuy
14402,"Age:[4, 6)",CHRYSLER,TRAILBLAZER,Bas,GREY,Covers,"Odo:(80000, 100000]","AAAP:(6000.0, 8000.0]",52598,NC,"VehBCost:(224.0, 5000.0]","WarrCost:(1800, 2600]",BadBuy,BadBuy,GoodBuy
14403,"Age:[2, 4)",CHRYSLER,LIBERTY,SE,BLACK,Covers,"Odo:(60000, 80000]","AAAP:(3000.0, 6000.0]",19638,FL,"VehBCost:(7000.0, 8000.0]","WarrCost:(461, 700]",BadBuy,GoodBuy,GoodBuy
14407,"Age:[2, 4)",GM,STRATUS,S,BLACK,Covers,"Odo:(60000, 80000]","AAAP:(8000.0, 10000.0]",16926,CA,"VehBCost:(5000.0, 7000.0]","WarrCost:(700, 1200]",BadBuy,GoodBuy,GoodBuy

In [57]:
df_ = pd.read_csv("kids_train_cleaned.csv")

In [59]:
df_.head()

,Unnamed: 0,RefId,IsBadBuy,PurchDate,Auction,VehYear,VehicleAge,Make,Model,Trim,...,PurchMonth,PurchDay,PurchWeekDay,EngineLiters,NumCylinders,4X4,WheelDrive,NumDoors,PCA1,PCA2
0,0,326,1,10/25/2010,ADESA,2008.0,2.0,KIA,SPECTRA,EX,...,10.0,25.0,Monday,4.11398,5.0,0,0,4.0,1797.080405,-753.566708
1,1,42991,0,5/27/2009,MANHEIM,2006.0,3.0,CHRYSLER,STRATUS,SXT,...,5.0,27.0,Wednesday,2.70000,6.0,0,0,4.0,-4879.356480,1637.798453
2,2,55273,0,3/18/2010,OTHER,2008.0,2.0,CHRYSLER,CALIBER,SE,...,3.0,18.0,Thursday,2.31289,6.0,0,0,4.0,4349.541129,-467.358818
3,3,29058,0,6/8/2009,OTHER,2005.0,4.0,FORD,FREESTAR,S,...,6.0,8.0,Monday,3.90000,6.0,NO,Front,5.0,-5514.286888,1633.449461
4,4,34991,0,3/4/2009,MANHEIM,2005.0,4.0,CHRYSLER,TOWN & COUNTRY V,Bas,...,3.0,4.0,Wednesday,3.30000,4.0,NO,Front,5.0,-4594.389176,1693.004506

In [62]:
df_.drop(df_.columns[0], axis=1, inplace=True)

In [63]:
df_.drop(columns= to_drop, axis=1, inplace=True)

In [64]:
df_.head()

,IsBadBuy,VehicleAge,Make,Model,Trim,Color,WheelType,VehOdo,AAAP,BYRNO,VNST,VehBCost,WarrantyCost
0,1,2.0,KIA,SPECTRA,EX,BLUE,Covers,61184,6796.0,5546,FL,6100.0,533
1,0,3.0,CHRYSLER,STRATUS,SXT,SILVER,Covers,92383,5480.0,99750,FL,4000.0,1630
2,0,2.0,CHRYSLER,CALIBER,SE,BLACK,Covers,45965,8067.0,99761,OK,7500.0,693
3,0,4.0,FORD,FREESTAR,S,BROWN,Covers,80169,4817.0,99761,AZ,4725.0,1633
4,0,4.0,CHRYSLER,TOWN & COUNTRY V,Bas,BLUE,Alloy,77372,5430.0,20833,TX,5670.0,1623

In [65]:
for col in categories:
    df_[col] = df_[col].astype('category')
    
df_['VehicleAge'] = df_['VehicleAge'].astype('int')

In [69]:
df_['WheelType'] = df_['WheelType'].astype('str')
df_['WheelType'].fillna('Unknown', inplace=True)
df_['WheelType'] = df_['WheelType'].astype('category')

In [70]:
sum_ = df_.isnull().sum()
sum_[sum_ != 0]

Series([], dtype: int64)

In [71]:
bins = [df_.VehBCost.min() - 1,5000, 7000, 8000, 10000, df_.VehBCost.max()]

df_['VehBCost'] = pd.cut(df_['VehBCost'], bins)

In [72]:
bins = [df_.AAAP.min() - 1, 3000, 6000, 8000, 10000, df_.AAAP.max()]

df_['AAAP'] = pd.cut(df_['AAAP'], bins)

In [73]:
bins = [df_.WarrantyCost.min() - 1,700, 1200, 1800, 2600, df_.WarrantyCost.max()]

df_['WarrantyCost'] = pd.cut(df_['WarrantyCost'], bins)

In [74]:
bins = [df_.VehOdo.min() - 1,40000, 60000, 80000, 100000, df_.VehOdo.max()]

df_['VehOdo'] = pd.cut(df_['VehOdo'], bins)

In [75]:
df_['VehicleAge'] = pd.cut(df_['VehicleAge'], [0, 2, 4, 6, 8, 10], right=False)

In [76]:
df_['VehicleAge'] = 'Age:' + df_['VehicleAge'].astype(str)
df_['VehOdo'] = 'Odo:' + df_['VehOdo'].astype(str)
df_['AAAP'] = 'AAAP:' + df_['AAAP'].astype(str)
df_['WarrantyCost'] = 'WarrCost:' + df_['WarrantyCost'].astype(str)
df_['VehBCost'] = 'VehBCost:' + df_['VehBCost'].astype(str)

df_['BuyStatus'] = df_['IsBadBuy'].map(
    {0: 'GoodBuy', 1: 'BadBuy'}).astype(str)
df_.drop(columns=['IsBadBuy'], inplace=True)

In [77]:
df_.head()

,VehicleAge,Make,Model,Trim,Color,WheelType,VehOdo,AAAP,BYRNO,VNST,VehBCost,WarrantyCost,BuyStatus
0,"Age:[2, 4)",KIA,SPECTRA,EX,BLUE,Covers,"Odo:(60000, 80000]","AAAP:(6000.0, 8000.0]",5546,FL,"VehBCost:(5000.0, 7000.0]","WarrCost:(461, 700]",BadBuy
1,"Age:[2, 4)",CHRYSLER,STRATUS,SXT,SILVER,Covers,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",99750,FL,"VehBCost:(224.0, 5000.0]","WarrCost:(1200, 1800]",GoodBuy
2,"Age:[2, 4)",CHRYSLER,CALIBER,SE,BLACK,Covers,"Odo:(40000, 60000]","AAAP:(8000.0, 10000.0]",99761,OK,"VehBCost:(7000.0, 8000.0]","WarrCost:(461, 700]",GoodBuy
3,"Age:[4, 6)",FORD,FREESTAR,S,BROWN,Covers,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",99761,AZ,"VehBCost:(224.0, 5000.0]","WarrCost:(1200, 1800]",GoodBuy
4,"Age:[4, 6)",CHRYSLER,TOWN & COUNTRY V,Bas,BLUE,Alloy,"Odo:(60000, 80000]","AAAP:(3000.0, 6000.0]",20833,TX,"VehBCost:(5000.0, 7000.0]","WarrCost:(1200, 1800]",GoodBuy

In [78]:
df_['PredictionLore'] = "NotPredicted"

In [79]:
df_['PredictionLore']  = np.where((np.logical_and(df_['AAAP'] == 'AAAP:(6000.0, 8000.0]' ,df_['WheelType'] == 'Covers')),str('GoodBuy'),df_['PredictionLore'] )

In [80]:
df_['PredictionLore']  = np.where((np.logical_and(df_['VehicleAge'] == 'Age:[2, 4)' ,df_['WheelType'] == 'Covers')),str('GoodBuy'),df_['PredictionLore'])

In [81]:
df_['PredictionLore']  = np.where(np.logical_and(df_['Make'] == 'CHRYSLER' ,df_['WheelType'] == 'Covers'),str('GoodBuy'),df_['PredictionLore'])

In [82]:
ppp = np.logical_and(df_['VehBCost'] == 'VehBCost:(224.0, 5000.0]' ,df_['AAAP'] == 'AAAP:(3000.0, 6000.0]')
df_['PredictionLore']  = np.where(np.logical_and(ppp, df_['PredictionLore'] == 'NotPredicted'),str('BadBuy'),df_['PredictionLore'])

In [83]:
len(df_)

58384

In [85]:
len(df_[df_['PredictionLore'] != 'NotPredicted'])

22976

In [84]:
df_temp = df_[df_['PredictionLore'] != 'NotPredicted']

In [86]:
len(df_temp)

22976

In [87]:
len(df_temp[df_temp['PredictionLore'] == df_temp['BuyStatus']])

18097

In [88]:
len(df_temp[df_temp.PredictionLore != df_temp.BuyStatus])

4879

In [89]:
18097/(4879+18097)

0.7876479805013927

In [90]:
df.head()

,VehicleAge,Make,Model,Trim,Color,WheelType,VehOdo,AAAP,BYRNO,VNST,VehBCost,WarrantyCost,BuyStatus,Predicted,PredictionLore
0,"Age:[4, 6)",KIA,SPECTRA,EX,GOLD,Covers,"Odo:(60000, 80000]","AAAP:(3000.0, 6000.0]",20740,NC,"VehBCost:(224.0, 5000.0]","WarrCost:(461, 700]",GoodBuy,BadBuy,BadBuy
1,"Age:[4, 6)",CHRYSLER,ION,Tou,SILVER,Covers,"Odo:(80000, 100000]","AAAP:(3000.0, 6000.0]",22808,TX,"VehBCost:(8000.0, 10000.0]","WarrCost:(1200, 1800]",GoodBuy,BadBuy,GoodBuy
2,"Age:[2, 4)",MAZDA,MAZDA3,i,SILVER,Alloy,"Odo:(40000, 60000]","AAAP:(10000.0, 35722.0]",99761,NH,"VehBCost:(7000.0, 8000.0]","WarrCost:(700, 1200]",GoodBuy,BadBuy,NotPredicted
3,"Age:[2, 4)",CHRYSLER,PT CRUISER,LE,SILVER,Covers,"Odo:(80000, 100000]","AAAP:(10000.0, 35722.0]",18822,TX,"VehBCost:(224.0, 5000.0]","WarrCost:(1200, 1800]",GoodBuy,GoodBuy,GoodBuy
4,"Age:[4, 6)",KIA,OPTIMA,EX,BLACK,Alloy,"Odo:(40000, 60000]","AAAP:(3000.0, 6000.0]",20207,TX,"VehBCost:(5000.0, 7000.0]","WarrCost:(461, 700]",GoodBuy,BadBuy,NotPredicted

In [92]:
len(df_temp[df_temp['PredictionLore'] == 'BadBuy'])

4541

In [93]:
len(df_temp[df_temp['PredictionLore'] == 'GoodBuy'])

18435

In [95]:
dfPene = df_temp[df_temp['PredictionLore'] == 'BadBuy']

In [97]:
len(dfPene[dfPene['BuyStatus'] != 'GoodBuy']) # TN

912

In [98]:
len(dfPene[dfPene['BuyStatus'] == 'GoodBuy']) # FN

3629

In [99]:
dfPene = df_temp[df_temp['PredictionLore'] == 'GoodBuy']

In [100]:
len(dfPene[dfPene['BuyStatus'] != 'GoodBuy']) # FP

1250

In [101]:
len(dfPene[dfPene['BuyStatus'] == 'GoodBuy']) # TP

17185

Cosa finale

In [104]:
df_['PredictionLore'] = np.where(df_['PredictionLore'] == 'NotPredicted', "GoodBuy", df_['PredictionLore'])

In [105]:
df_['PredictionLore'].unique()

array(['GoodBuy', 'BadBuy'], dtype=object)

In [106]:
df_temp = df_

In [108]:
len(df_temp[df_temp['PredictionLore'] == df_temp['BuyStatus']])

48460

In [109]:
len(df_temp[df_temp['PredictionLore'] != df_temp['BuyStatus']])

9924

In [110]:
48460/(48460+9924)

0.8300219238147437

In [107]:
dfPene = df_temp[df_temp['PredictionLore'] == 'BadBuy']

In [111]:
len(dfPene[dfPene['BuyStatus'] != 'GoodBuy']) # TN

912

In [112]:
len(dfPene[dfPene['BuyStatus'] == 'GoodBuy']) # FN

3629

In [113]:
dfPene = df_temp[df_temp['PredictionLore'] == 'GoodBuy']

In [114]:
len(dfPene[dfPene['BuyStatus'] != 'GoodBuy']) # FP

6295

In [115]:
len(dfPene[dfPene['BuyStatus'] == 'GoodBuy']) # TP

47548